/*
 * generated by Xtext
 */
package com.bundleDsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractBundleDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.bundleDsl.bundleDsl.BundleDslPackage.eINSTANCE);
		return result;
	}
}
