/**
 * generated by Xtext
 */
package com.bundleDsl.ui.contentassist;

import com.bundleDsl.ui.contentassist.AbstractBundleDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BundleDslProposalProvider extends AbstractBundleDslProposalProvider {
}
