/**
 * generated by Xtext
 */
package com.bundleDsl.validation;

import com.bundleDsl.validation.AbstractBundleDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BundleDslValidator extends AbstractBundleDslValidator {
}
