/*
 * generated by Xtext
 */
package com.bundleDsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BundleDslUiModule extends com.bundleDsl.ui.AbstractBundleDslUiModule {
	public BundleDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
