/*
 * generated by Xtext
 */
package com.bundleDsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BundleDslRuntimeModule extends com.bundleDsl.AbstractBundleDslRuntimeModule {

}
